# Generated by Django 3.0.2 on 2020-02-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_list', '0002_auto_20200203_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='photo',
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=20),
        ),
    ]
