# Generated by Django 3.0.2 on 2020-02-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_list', '0003_auto_20200203_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='photo',
            field=models.ImageField(default='media/no-img.jpg', upload_to='media/'),
        ),
    ]
