# Generated by Django 3.0.2 on 2020-02-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_list', '0004_users_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='photo',
            field=models.ImageField(default='media/image/no-img.jpg', upload_to='media/'),
        ),
    ]
