# Generated by Django 3.0.2 on 2020-02-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_list', '0005_auto_20200206_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='photo',
            field=models.ImageField(default='media/image/no-img.jpg', upload_to='media/image/'),
        ),
    ]
