# Generated by Django 3.0.2 on 2020-02-06 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_list', '0012_auto_20200206_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
